namespace LP2_P1
{
    public enum TitleGenre
    {
        ACTION,
        ADULT,
        ADVENTURE,
        ANIMATION,
        BIOGRAPHY,
        COMEDY,
        CRIME,
        DOCUMENTARY,
        DRAMA,
        FAMILY,
        FANTASY,
        FILMNOIR,
        GAMESHOW,
        HISTORY,
        HORROR,
        MUSIC,
        MUSICAL,
        MYSTERY,
        NEWS,
        REALITYTV,
        ROMANCE,
        SCIFI,
        SHORT,
        SPORT,
        TALKSHOW,
        THRILLER,
        WAR,
        WESTERN
    }
}
