namespace LP2_P1
{
    public enum TitleGenre
    {
        DOCUMENTARY,
        SHORT,
        ANIMATION,
        COMEDY,
        ROMANCE,
        SPORT,
        ACTION,
        NEWS,
        DRAMA,
        FANTASY,
        HORROR,
        BIOGRAPHY,
        MUSIC,
        WAR,
        CRIME,
        WESTERN,
        FAMILY,
        ADVENTURE,
        HISTORY,
        MYSTERY,
        SCIFI,
        THRILLER,
        MUSICAL,
        FILMNOIR,
        GAMESHOW,
        TALKSHOW,
        REALITYTV,
        ADULT
    }
}
